version: "3.9"

services:
  # Baza de date PostgreSQL
  db:
    image: postgres:15
    container_name: medical_db
    environment:
      POSTGRES_USER: ${DB_USER:-scd}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-scd}
      POSTGRES_DB: ${DB_NAME:-clinica}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - db-net
    # testare bd daca e up si merge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-scd} -d ${DB_NAME:-clinica}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Keycloak pentru autentificare
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: scd
      KC_DB_PASSWORD: scd
      KC_HOSTNAME_STRICT: false
      KC_HTTP_ENABLED: true
    # import realm clinicai la pornire
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    # conditie pt keycloak sa porneasca doar dupa ce db e
    # si el up pt ca altfel ar pica
    depends_on:
      db:
        condition: service_healthy
    networks:
      - auth-net
      - db-net
    # montam fisierul de export al realm-ului
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm.json

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - internal-net

  # User Service
  user-service:
    build: ./user-service
    container_name: user_service
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scd}:${DB_PASSWORD:-scd}@db:5432/${DB_NAME:-clinica}
      FLASK_ENV: development
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: ${KEYCLOAK_REALM:-medical-clinica}
      KEYCLOAK_CLIENT_ID: medical-app
      KEYCLOAK_BACKEND_CLIENT_ID: ${KEYCLOAK_BACKEND_CLIENT_ID:-medical-backend}
      KEYCLOAK_BACKEND_CLIENT_SECRET: ${KEYCLOAK_BACKEND_CLIENT_SECRET:-secret-backend}
    depends_on:
      - db
      - keycloak
    ports:
      - "5001:5000"
    networks:
      - internal-net
      - db-net
      - auth-net
    volumes:
      - ./user-service:/app
    command: python app.py

  # Doctor Service
  doctor-service:
    build: ./doctor-service
    container_name: doctor_service
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scd}:${DB_PASSWORD:-scd}@db:5432/${DB_NAME:-clinica}
      FLASK_ENV: development  
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: medical-clinica
      KEYCLOAK_CLIENT_ID: medical-app 
      KEYCLOAK_BACKEND_CLIENT_ID: ${KEYCLOAK_BACKEND_CLIENT_ID:-medical-backend}
      KEYCLOAK_BACKEND_CLIENT_SECRET: ${KEYCLOAK_BACKEND_CLIENT_SECRET:-secret-backend}
    depends_on:
      - db
      - keycloak
    ports:
      - "5002:5000"
    networks:
      - internal-net
      - db-net
      - auth-net
    volumes:
      - ./doctor-service:/app

  appointment-service:
    build: ./appointment-service
    container_name: appointment_service
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scd}:${DB_PASSWORD:-scd}@db:5432/${DB_NAME:-clinica}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: medical-clinica
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db
      - keycloak
      - rabbitmq
    ports:
      - "5003:5000"
    networks:
      - internal-net
      - db-net
      - auth-net
    volumes:
      - ./appointment-service:/app

  # consumatorul pentru programari
  appointment-worker:
    build: ./appointment-service
    container_name: appointment_worker
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scd}:${DB_PASSWORD:-scd}@db:5432/${DB_NAME:-clinica}
      RABBITMQ_HOST: rabbitmq
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - rabbitmq
    networks:
      - internal-net
      - db-net
    volumes:
      - ./appointment-service:/app
    command: python worker.py

  # Server de mail pt simulare
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # cosola web vad in timp real
    networks:
      - internal-net

  notification-service:
    build: ./notification-service
    container_name: notification_service
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scd}:${DB_PASSWORD:-scd}@db:5432/${DB_NAME:-clinica}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: medical-clinica
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - keycloak
      - mailhog
    ports:
      - "5004:5000"
    networks:
      - internal-net
      - db-net
      - auth-net
    volumes:
      - ./notification-service:/app
    command: gunicorn --bind 0.0.0.0:5000 --workers 2 'app:create_app()'

  # consumatorul pentru mailuri
  notification-worker:
    build: ./notification-service
    container_name: notification_worker
    environment:
      DATABASE_URL: postgresql://${DB_USER:-scd}:${DB_PASSWORD:-scd}@db:5432/${DB_NAME:-clinica}
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_REALM: medical-clinica
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      PYTHONUNBUFFERED: 1
    depends_on:
      - db
      - rabbitmq
      - mailhog
    networks:
      - internal-net
      - db-net 
    volumes:
      - ./notification-service:/app
    command: python worker.py

  # MinIO
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001" # consola web
    networks:
      - internal-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5

  # proces pentru crearea automata a bucket-ului pentru minio
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    networks:
      - internal-net
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin; do
        echo 'astept MinIO sa porneasca'
        sleep 1
      done;

      /usr/bin/mc mb --ignore-existing myminio/confirmations;
      /usr/bin/mc anonymous set download myminio/confirmations;
      
      echo 'Bucket configurat cu succes!';
      exit 0;
      "
networks:
  db-net:
    driver: bridge
  auth-net:
    driver: bridge
  internal-net:
    driver: bridge

volumes:
  db_data:
  minio_data: